# Generated by Django 3.2.3 on 2021-05-26 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arkeo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meteostation',
            options={'ordering': ['name']},
        ),
    ]
