# Generated by Django 3.2.3 on 2021-05-26 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('start', models.IntegerField()),
                ('st_type', models.CharField(choices=[('Automated observational station', 'Automated observational station'), ('Manned synoptic station', 'Manned synoptic station'), ('Virtual station', 'Virtual station')], default='Not defined', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
