# Generated by Django 3.2.3 on 2021-05-27 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arkeo', '0002_alter_meteostation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteostation',
            name='owner',
            field=models.ForeignKey(default='berthakim', on_delete=django.db.models.deletion.CASCADE, related_name='stations', to=settings.AUTH_USER_MODEL),
        ),
    ]
