# Generated by Django 3.2.3 on 2021-11-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arkeo', '0004_alter_meteostation_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meteostation',
            options={'ordering': ['-id']},
        ),
    ]
